# Generated by Django 5.2.17 on 2026-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asociado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_asociado",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "numero_usuario",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "tipo_persona",
                    models.CharField(
                        choices=[
                            ("real", "De existencia real"),
                            ("ideal", "De existencia ideal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "nombre_apellido",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre y apellido"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Femenino"),
                            ("M", "Masculino"),
                            ("X", "No binario"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razón social"
                    ),
                ),
                (
                    "tipo_organismo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de organismo"
                    ),
                ),
                (
                    "fecha_nacimiento_constitucion",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de nacimiento / constitución",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=11, verbose_name="N° de documento"),
                ),
                (
                    "cuit",
                    models.CharField(blank=True, max_length=11, verbose_name="CUIT"),
                ),
                (
                    "condicion_iva",
                    models.CharField(
                        choices=[
                            ("consumidor_final", "Consumidor Final"),
                            ("monotributista", "Monotributista"),
                            ("responsable_inscripto", "Responsable Inscripto"),
                        ],
                        max_length=30,
                        verbose_name="Condición de IVA",
                    ),
                ),
                ("domicilio", models.CharField(max_length=255)),
                (
                    "estado_societario",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                    ),
                ),
                ("fecha_ingreso", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["numero_asociado"],
            },
        ),
    ]
