# Generated by Django 5.2.17 on 2026-09-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_acciones_inicial', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Parámetro de suscripción',
                'verbose_name_plural': 'Parámetros de suscripción',
            },
        ),
        migrations.CreateModel(
            name='ValorNominalAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente_desde', models.DateField()),
            ],
            options={
                'verbose_name': 'Valor nominal de la acción',
                'verbose_name_plural': 'Valores nominales de la acción',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titulo', models.CharField(editable=False, max_length=10, unique=True)),
                ('cantidad_acciones', models.PositiveIntegerField()),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_suscripto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_suscripcion', models.DateField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='core.asociado')),
            ],
            options={
                'verbose_name': 'Suscripción de acciones',
                'verbose_name_plural': 'Suscripciones de acciones',
                'ordering': ['numero_titulo'],
            },
        ),
    ]
