# Generated by Django 5.2.17 on 2026-09-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parametrosuscripcion_valornominalaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asociado',
            name='celular',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='asociado',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='asociado',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email alternativo'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='es_proveedor',
            field=models.BooleanField(default=False, verbose_name='Es proveedor'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asociado',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asociado',
            name='provincia',
            field=models.CharField(blank=True, default='Buenos Aires', max_length=100),
        ),
        migrations.AddField(
            model_name='asociado',
            name='ruta_subruta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ruta / subruta'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono fijo'),
        ),
    ]
