# Generated by Django 5.2.17 on 2026-09-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asociado_categoria_asociado_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suministros_como_socio', to='core.asociado', verbose_name='Socio')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suministros_como_titular', to='core.asociado', verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'Suministro',
                'verbose_name_plural': 'Suministros',
            },
        ),
    ]
